apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: aws-s3-streaming-upload-sink
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "AWS S3 Streaming upload Sink"
    description: |-
      Upload data to AWS S3 in streaming upload mode.
    required:
      - bucketNameOrArn
      - accessKey
      - secretKey
      - region
      - keyName
    type: object
    properties:
      bucketNameOrArn:
        title: Bucket Name
        description: The S3 Bucket name or ARN.
        type: string
      accessKey:
        title: Access Key
        description: The access key obtained from AWS.
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      secretKey:
        title: Secret Key
        description: The secret key obtained from AWS.
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      region:
        title: AWS Region
        description: The AWS region to connect to.
        type: string
        example: eu-west-1
      autoCreateBucket:
        title: Autocreate Bucket
        description: Setting the autocreation of the S3 bucket bucketName.
        type: boolean
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:checkbox'
        default: false
      streamingUploadMode:
        title: Streaming Upload Mode
        description: Setting the Streaming Upload Mode
        type: boolean
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:checkbox'
        default: true
      restartingPolicy:
        title: Restarting Policy
        description: The restarting policy to use in streaming upload mode. There are 2 enums and the value can be one of override, lastPart
        type: string
        default: "lastPart"
      batchMessageNumber:
        title: Batch Message Number
        description: The number of messages composing a batch in streaming upload mode
        type: int
        default: 10
      batchSize:
        title: Batch Size
        description: The batch size (in bytes) in streaming upload mode
        type: int
        default: 1000000
      namingStrategy:
        title: Naming Strategy
        description: The naming strategy to use in streaming upload mode. There are 2 enums and the value can be one of progressive, random
        type: string
        default: "progressive"
      keyName:
        title: Key Name
        description: Setting the key name for an element in the bucket through endpoint parameter. In Streaming Upload, with the default configuration, this will be the base for the progressive creation of files.
        type: string
      overrideEndpoint:
        title: Koverride
        description: override
        type: boolean
      endpoint:
        title: endpoint
        description: override
        type: string
  dependencies:
    - "camel:aws2-s3"
    - "camel:kamelet"
  flow:
    from:
      uri: "kamelet:source"
      steps:
      - to:
          uri: "aws2-s3:{{bucketNameOrArn}}"
          parameters:
            secretKey: "{{secretKey}}"
            accessKey: "{{accessKey}}"
            region: "{{region}}"
            autoCreateBucket: "{{autoCreateBucket}}"
            streamingUploadMode: "{{streamingUploadMode}}"
            restartingPolicy: "{{restartingPolicy}}"
            batchMessageNumber: "{{batchMessageNumber}}"
            batchSize: "{{batchSize}}"
            namingStrategy: "{{namingStrategy}}"
            keyName: "{{keyName}}"
            overrideEndpoint: "{{?overrideEndpoint}}"
            uriEndpointOverride: "{{?endpoint}}"

